name: Scrape latest conditions

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "15 5,13,21 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Download latest data
        run: python sunday_river_status.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
